"""add created_by, brief_text to tasks and ru enum

Revision ID: 10f77fa75d23
Revises: 3982f50872da
Create Date: 2025-10-20 00:02:51.124936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10f77fa75d23'
down_revision: Union[str, None] = '3982f50872da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.add_column('tasks', sa.Column('brief_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'brief_text')
    op.drop_column('tasks', 'created_by')
    # ### end Alembic commands ###
