"""store statuses in russian

Revision ID: 3982f50872da
Revises: 5b54ed94a0b8
Create Date: 2025-10-19 23:23:40.087839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3982f50872da'
down_revision: Union[str, None] = '5b54ed94a0b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('new', 'drafting_tz_kp', 'sourcing_devs', 'selecting_devs', 'send_tz_to_client', 'create_group', 'in_dev', 'done', 'cancelled', name='projectstatus'),
               type_=sa.Enum('новый', 'составляется тз/кп', 'ищем разработчиков', 'выбираем разработчиков', 'высылаем тз заказчику', 'создаём группу', 'в разработке', 'готово', 'отменён', name='projectstatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('новый', 'составляется тз/кп', 'ищем разработчиков', 'выбираем разработчиков', 'высылаем тз заказчику', 'создаём группу', 'в разработке', 'готово', 'отменён', name='projectstatus', native_enum=False),
               type_=postgresql.ENUM('new', 'drafting_tz_kp', 'sourcing_devs', 'selecting_devs', 'send_tz_to_client', 'create_group', 'in_dev', 'done', 'cancelled', name='projectstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
