"""add column project_type

Revision ID: d7638d6c47d3
Revises: e40ea1e8cb99
Create Date: 2025-10-25 11:11:07.291605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7638d6c47d3'
down_revision: Union[str, None] = 'e40ea1e8cb99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('project_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'project_type')
    # ### end Alembic commands ###
